code-insiders --install-extension 42Crunch.vscode-openapi
code-insiders --install-extension aaron-bond.better-comments
code-insiders --install-extension adpyke.codesnap
code-insiders --install-extension adpyke.js-unicode-preview
code-insiders --install-extension alefragnani.Bookmarks
code-insiders --install-extension azps-tools.azps-tools
code-insiders --install-extension AzurePolicy.azurepolicyextension
code-insiders --install-extension Azurite.azurite
code-insiders --install-extension bencoleman.armview
code-insiders --install-extension brunnerh.insert-unicode
code-insiders --install-extension christian-kohler.npm-intellisense
code-insiders --install-extension christian-kohler.path-intellisense
code-insiders --install-extension CodeStream.codestream
code-insiders --install-extension damienaicheh.azure-devops-snippets
code-insiders --install-extension DavidAnson.vscode-markdownlint
code-insiders --install-extension dawhite.mustache
code-insiders --install-extension donjayamanne.githistory
code-insiders --install-extension eamodio.gitlens
code-insiders --install-extension formulahendry.auto-close-tag
code-insiders --install-extension formulahendry.auto-rename-tag
code-insiders --install-extension formulahendry.docker-explorer
# code-insiders --install-extension GitHub.copilot
code-insiders --install-extension GitHub.github-vscode-theme
code-insiders --install-extension hashicorp.terraform
code-insiders --install-extension humao.rest-client
code-insiders --install-extension jamesohortle.unicodehover
code-insiders --install-extension jeff-hykin.polacode-2019
code-insiders --install-extension jeffersonlicet.snipped
code-insiders --install-extension jspolancor.presentationmode
code-insiders --install-extension mermade.openapi-lint
code-insiders --install-extension mhutchie.git-graph
code-insiders --install-extension mindaro-dev.file-downloader
code-insiders --install-extension mindaro.mindaro
code-insiders --install-extension ms-azure-devops.azure-pipelines
code-insiders --install-extension ms-azurecache.vscode-azurecache
code-insiders --install-extension ms-azuretools.azure-dev
code-insiders --install-extension ms-azuretools.azure-video-analyzer
code-insiders --install-extension ms-azuretools.vscode-apimanagement
code-insiders --install-extension ms-azuretools.vscode-azureappservice
code-insiders --install-extension ms-azuretools.vscode-azurecontainerapps
code-insiders --install-extension ms-azuretools.vscode-azureeventgrid
code-insiders --install-extension ms-azuretools.vscode-azurefunctions
code-insiders --install-extension ms-azuretools.vscode-azurelogicapps
code-insiders --install-extension ms-azuretools.vscode-azureresourcegroups
code-insiders --install-extension ms-azuretools.vscode-azurestaticwebapps
code-insiders --install-extension ms-azuretools.vscode-azurestorage
code-insiders --install-extension ms-azuretools.vscode-azureterraform
code-insiders --install-extension ms-azuretools.vscode-azurevirtualmachines
code-insiders --install-extension ms-azuretools.vscode-bicep
code-insiders --install-extension ms-azuretools.vscode-cosmosdb
code-insiders --install-extension ms-azuretools.vscode-dapr
code-insiders --install-extension ms-azuretools.vscode-docker
code-insiders --install-extension ms-azuretools.vscode-logicapps
code-insiders --install-extension ms-databasemigration.data-access-migration-toolkit
code-insiders --install-extension ms-dotnettools.csharp
code-insiders --install-extension ms-dotnettools.dotnet-interactive-vscode
code-insiders --install-extension ms-dotnettools.vscode-dotnet-runtime
code-insiders --install-extension ms-edgedevtools.vscode-edge-devtools
code-insiders --install-extension ms-kubernetes-tools.aks-devx-tools
code-insiders --install-extension ms-kubernetes-tools.vscode-aks-tools
code-insiders --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code-insiders --install-extension ms-mssql.data-workspace-vscode
code-insiders --install-extension ms-mssql.mssql
code-insiders --install-extension ms-mssql.sql-bindings-vscode
code-insiders --install-extension ms-mssql.sql-database-projects-vscode
code-insiders --install-extension ms-python.black-formatter
code-insiders --install-extension ms-python.isort
code-insiders --install-extension ms-python.python
code-insiders --install-extension ms-python.vscode-pylance
code-insiders --install-extension ms-toolsai.jupyter
code-insiders --install-extension ms-toolsai.jupyter-keymap
code-insiders --install-extension ms-toolsai.jupyter-renderers
code-insiders --install-extension ms-toolsai.vscode-ai
code-insiders --install-extension ms-toolsai.vscode-ai-inference
code-insiders --install-extension ms-toolsai.vscode-ai-remote
code-insiders --install-extension ms-toolsai.vscode-jupyter-cell-tags
code-insiders --install-extension ms-toolsai.vscode-jupyter-slideshow
code-insiders --install-extension ms-vscode-remote.remote-containers
code-insiders --install-extension ms-vscode-remote.remote-wsl
code-insiders --install-extension ms-vscode-remote.vscode-remote-extensionpack
code-insiders --install-extension ms-vscode.azure-account
code-insiders --install-extension ms-vscode.azure-sphere-tools
code-insiders --install-extension ms-vscode.azure-sphere-tools-ui
code-insiders --install-extension ms-vscode.azurecli
code-insiders --install-extension ms-vscode.cmake-tools
code-insiders --install-extension ms-vscode.cpptools
code-insiders --install-extension ms-vscode.hexeditor
code-insiders --install-extension ms-vscode.live-server
code-insiders --install-extension ms-vscode.powershell
code-insiders --install-extension ms-vscode.remote-explorer
code-insiders --install-extension ms-vscode.remote-server
code-insiders --install-extension ms-vsliveshare.vsliveshare
code-insiders --install-extension msazurermtools.azurerm-vscode-tools
code-insiders --install-extension philosowaffle.openapi-designer
code-insiders --install-extension quantum.quantum-devkit-vscode
code-insiders --install-extension rangav.vscode-thunder-client
code-insiders --install-extension redhat.java
code-insiders --install-extension redhat.vscode-commons
code-insiders --install-extension redhat.vscode-yaml
code-insiders --install-extension ritwickdey.LiveServer
code-insiders --install-extension shd101wyy.markdown-preview-enhanced
code-insiders --install-extension spmeesseman.vscode-vslauncher
code-insiders --install-extension streetsidesoftware.code-spell-checker
code-insiders --install-extension twxs.cmake
code-insiders --install-extension usqlextpublisher.usql-vscode-ext
code-insiders --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code-insiders --install-extension VisualStudioExptTeam.vscodeintellicode
code-insiders --install-extension VisualStudioOnlineApplicationInsights.application-insights
code-insiders --install-extension vsciot-vscode.azure-iot-edge
code-insiders --install-extension vsciot-vscode.azure-iot-toolkit
code-insiders --install-extension vsciot-vscode.vscode-dtdl
code-insiders --install-extension vsciot-vscode.vscode-iot-device-cube
code-insiders --install-extension vscjava.vscode-java-debug
code-insiders --install-extension vscjava.vscode-java-dependency
code-insiders --install-extension vscjava.vscode-java-pack
code-insiders --install-extension vscjava.vscode-java-test
code-insiders --install-extension vscjava.vscode-maven
code-insiders --install-extension wilfriedwoivre.arm-params-generator
code-insiders --install-extension yzhang.markdown-all-in-one
code-insiders --install-extension zoellner.openapi-preview
code-insiders --install-extension GitHub.copilot-nightly
code-insiders --install-extension bierner.markdown-mermaid
code-insiders --install-extension ms-dotnettools.csdevkit