code --install-extension 42Crunch.vscode-openapi
code --install-extension aaron-bond.better-comments
code --install-extension adpyke.codesnap
code --install-extension adpyke.js-unicode-preview
code --install-extension alefragnani.Bookmarks
code --install-extension azps-tools.azps-tools
code --install-extension AzurePolicy.azurepolicyextension
code --install-extension Azurite.azurite
code --install-extension bencoleman.armview
code --install-extension brunnerh.insert-unicode
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension CodeStream.codestream
code --install-extension damienaicheh.azure-devops-snippets
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dawhite.mustache
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.docker-explorer
code --install-extension GitHub.copilot
code --install-extension GitHub.github-vscode-theme
code --install-extension hashicorp.terraform
code --install-extension humao.rest-client
code --install-extension jamesohortle.unicodehover
code --install-extension jeff-hykin.polacode-2019
code --install-extension jeffersonlicet.snipped
code --install-extension jspolancor.presentationmode
code --install-extension mermade.openapi-lint
code --install-extension mhutchie.git-graph
code --install-extension mindaro-dev.file-downloader
code --install-extension mindaro.mindaro
code --install-extension ms-azure-devops.azure-pipelines
code --install-extension ms-azurecache.vscode-azurecache
code --install-extension ms-azuretools.azure-dev
code --install-extension ms-azuretools.azure-video-analyzer
code --install-extension ms-azuretools.vscode-apimanagement
code --install-extension ms-azuretools.vscode-azureappservice
code --install-extension ms-azuretools.vscode-azurecontainerapps
code --install-extension ms-azuretools.vscode-azureeventgrid
code --install-extension ms-azuretools.vscode-azurefunctions
code --install-extension ms-azuretools.vscode-azurelogicapps
code --install-extension ms-azuretools.vscode-azureresourcegroups
code --install-extension ms-azuretools.vscode-azurestaticwebapps
code --install-extension ms-azuretools.vscode-azurestorage
code --install-extension ms-azuretools.vscode-azureterraform
code --install-extension ms-azuretools.vscode-azurevirtualmachines
code --install-extension ms-azuretools.vscode-bicep
code --install-extension ms-azuretools.vscode-cosmosdb
code --install-extension ms-azuretools.vscode-dapr
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-azuretools.vscode-logicapps
code --install-extension ms-databasemigration.data-access-migration-toolkit
code --install-extension ms-dotnettools.csharp
code --install-extension ms-dotnettools.dotnet-interactive-vscode
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-edgedevtools.vscode-edge-devtools
code --install-extension ms-kubernetes-tools.aks-devx-tools
code --install-extension ms-kubernetes-tools.vscode-aks-tools
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-mssql.data-workspace-vscode
code --install-extension ms-mssql.mssql
code --install-extension ms-mssql.sql-bindings-vscode
code --install-extension ms-mssql.sql-database-projects-vscode
code --install-extension ms-python.black-formatter
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-ai
code --install-extension ms-toolsai.vscode-ai-inference
code --install-extension ms-toolsai.vscode-ai-remote
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.azure-sphere-tools
code --install-extension ms-vscode.azure-sphere-tools-ui
code --install-extension ms-vscode.azurecli
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.hexeditor
code --install-extension ms-vscode.live-server
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-server
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msazurermtools.azurerm-vscode-tools
code --install-extension philosowaffle.openapi-designer
code --install-extension quantum.quantum-devkit-vscode
code --install-extension rangav.vscode-thunder-client
code --install-extension redhat.java
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.LiveServer
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension spmeesseman.vscode-vslauncher
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension twxs.cmake
code --install-extension usqlextpublisher.usql-vscode-ext
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension VisualStudioOnlineApplicationInsights.application-insights
code --install-extension vsciot-vscode.azure-iot-edge
code --install-extension vsciot-vscode.azure-iot-toolkit
code --install-extension vsciot-vscode.vscode-dtdl
code --install-extension vsciot-vscode.vscode-iot-device-cube
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension wilfriedwoivre.arm-params-generator
code --install-extension yzhang.markdown-all-in-one
code --install-extension zoellner.openapi-preview
code --install-extension GitHub.copilot-nightly
code --install-extension bierner.markdown-mermaid
code --install-extension ms-dotnettools.csdevkit